/* Generated By:JavaCC: Do not edit this line. compConstants.java */
package Comp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Mayor = 1;
  /** RegularExpression Id. */
  int Menor = 2;
  /** RegularExpression Id. */
  int MayorIgual = 3;
  /** RegularExpression Id. */
  int MenorIgual = 4;
  /** RegularExpression Id. */
  int Comparacion = 5;
  /** RegularExpression Id. */
  int Diferente = 6;
  /** RegularExpression Id. */
  int Asignacion = 7;
  /** RegularExpression Id. */
  int Mas = 8;
  /** RegularExpression Id. */
  int Menos = 9;
  /** RegularExpression Id. */
  int ParAP = 10;
  /** RegularExpression Id. */
  int ParCi = 11;
  /** RegularExpression Id. */
  int Izq = 12;
  /** RegularExpression Id. */
  int Der = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int PUBLIC = 15;
  /** RegularExpression Id. */
  int clase = 16;
  /** RegularExpression Id. */
  int PRIVATE = 17;
  /** RegularExpression Id. */
  int False = 18;
  /** RegularExpression Id. */
  int True = 19;
  /** RegularExpression Id. */
  int integer = 20;
  /** RegularExpression Id. */
  int Dou = 21;
  /** RegularExpression Id. */
  int St = 22;
  /** RegularExpression Id. */
  int Ch = 23;
  /** RegularExpression Id. */
  int If = 24;
  /** RegularExpression Id. */
  int Boolean = 25;
  /** RegularExpression Id. */
  int Int = 26;
  /** RegularExpression Id. */
  int UNKNOWN = 27;
  /** RegularExpression Id. */
  int IDENTIFIER = 28;
  /** RegularExpression Id. */
  int Char = 29;
  /** RegularExpression Id. */
  int String = 30;
  /** RegularExpression Id. */
  int Double = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"public\"",
    "\"class\"",
    "\"private\"",
    "\"false\"",
    "\"true\"",
    "\"int\"",
    "\"double\"",
    "\"String\"",
    "\"char\"",
    "\"if\"",
    "\"boolean\"",
    "<Int>",
    "<UNKNOWN>",
    "<IDENTIFIER>",
    "<Char>",
    "<String>",
    "<Double>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
